### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Vlandoid** [Gimu/companion-for-bdo-translation#8]
"Обновление" not "обнавление" in ingame timer settings on Russian language

**Comment by seefalert** [comment]
Typo. Apparently I did not notice when translated. Thank you for your
observation!

сб, 9 июня 2018, 2:57 AM Vlandoid <notifications@github.com>:

**Comment by BanhmiDev** [comment]
Updated via merge 022726e40886ecb52a7cc4776c7522ba9f9eba1a
